name: PR Chunker

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  issues: write
  pull-requests: write
  repository-projects: write

jobs:
  chunk-and-review:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r scripts/pr_review/requirements.txt

      - name: Generate review chunks
        id: generate-chunks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/pr_review/chunker.py \
            --repo ${{ github.repository }} \
            --pr ${{ github.event.number }} \
            --base ${{ github.event.pull_request.base.sha }} \
            --head ${{ github.event.pull_request.head.sha }} \
            --output chunks.md \
            --github-token ${{ secrets.GITHUB_TOKEN }}

      - name: Post PR comment
        if: steps.generate-chunks.outcome == 'success'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const content = fs.readFileSync('chunks.md', 'utf8');
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: content
            });

      - name: Create review issue
        if: steps.generate-chunks.outcome == 'success'
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "PR#${{ github.event.number }} Review Assignments"
          content-filepath: ./chunks.md
          labels: "code-review"
          assignees: ${{ github.event.pull_request.requested_reviewers.*.login }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Post failure notice
        if: steps.generate-chunks.outcome != 'success'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `❌ Automatic chunking failed\n\nPlease review manually: ${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.number }}`
            });